name: Build Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
          architecture: x64
      - name: Build with Maven
        run: mvn clean install
      - name: Create Code Coverage
        uses: codecov/codecov-action@v2.0.2
        with:
          token: ${{ secrets.CODE_COVERAGE_TOKEN }}
          file: ./target/site/jacoco/jacoco.xml
          fail_ci_if_error: true
          verbose: true
